Csc bdse task2
au-spring-2018-bdse-lms/csc-bdse pull request #2
Opened 2018-03-15 21:01 UTC by yeputons

2018-03-17 16:14 UTC, 747mmHg requested changes
Две основных проблемы:
1. Сделана только половина задания — второй версии API (с поддержкой никнеймов и поиска по ним) я не нашел.
2. Из-за того, что вы добавили uid, стало возможно редактировать записи, а это может привести к неконсистентности вторичных индексов. Например такой сценарий: 1) делаем PUT с uid = 1 и фамилией A 2) делаем PUT с uid = 1 и фамилией B (что с точки зрения пользователя должно быть перезаписью первого значения) 3) запрашиваем всех пользователей, чья фамилия начинается на A и получаем uid 1. Надо либо решить в исходной постановка (где фамилия — это часть первичного ключа), либо консистентно обновлять индексы.

2018-03-24 20:39 UTC, alesavin requested changes
Доделаете?

2018-03-28 17:43 UTC, yeputons commented
Да, доделаем. Про первичный ключ мы из условия задания не поняли, решили добавить свой, проблема с обновлением возникла неожиданно, спасибо.

2018-04-01 22:09 UTC, alesavin commented
Принято без доделок, но балл невелик

2018-04-05 17:15 UTC, merged