Csc bdse task3
au-spring-2018-bdse-lms/csc-bdse pull request #4
Opened 2018-04-05 23:28 UTC by yeputons

2018-04-09 09:58 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/LastTimestampConflictResolver.java
> +            // TODO: what if timestamps coincide?
Поведение не определено в этом случае.
Сама по себе стратегия "Last Write Wins" - довольно бедная, но часто используется в силу простоты реализации и понимания.

2018-04-09 10:01 UTC, dormidon commented on INSTALL_TASK3.md
> +* Специфика сборки: должен быть доступен `protoc` в PATH (это компилятор для Google Protobuf).
Можно сделать гибче использование protobuf - не требовать предварительной установки компилятора, а так же иметь возможность запуска на разных ОС.
Для этого добавляем плагин:
```
<plugin>
  <groupId>org.xolstice.maven.plugins</groupId>
  <artifactId>protobuf-maven-plugin</artifactId>
  <version>0.5.1</version>
  <extensions>true</extensions>
  <configuration>
    <checkStaleness>true</checkStaleness>
    <protocArtifact>
      com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}
    </protocArtifact>
  </configuration>
</plugin>
```

А так же добавляем определение операционной системы (оно выполнит заполнение свойства `${os.detected.classifier}`):
```
<build>
  ...
  
  <extensions>
    <extension>
      <groupId>kr.motd.maven</groupId>
      <artifactId>os-maven-plugin</artifactId>
      <version>1.3.0.Final</version>
    </extension>
 </extensions>
</build>
```

Не нужно будет лишних требований к окружению, инструкций, а на десерт - запуск на разных OS из коробки.

2018-04-09 10:03 UTC, dormidon commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/ContaineredReplicasTest.java
> +    private static final int REPLICAS = 3;
Я правильно понял, что это один тест с фиксированным `RF`, `WCL`, `RCL`?
Можно ли сделать эти значения параметрами теста и запускать один и тот же тест, но с разными параметрами?

2018-04-09 10:06 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/ConflictResolver.java
> +    public Distributed.VersionedRecord resolve(List<Distributed.VersionedRecord> records);
Почему на вход принимается список записей? Важен ли нам их порядок?

2018-04-09 10:07 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/Coordinator.java
> +    private final int replicasCount;
А разве в `ClusterConfiguration` нет количества реплик?

2018-04-09 10:08 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/Coordinator.java
> +    private final int replicasCount;
Туплю. Вижу, что так и используется.

2018-04-09 10:09 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/Coordinator.java
> +            executorServices[i] = Executors.newSingleThreadExecutor();
`SingleThreadExecutor` - не самое удачный выбор. 
Если конкретный узел затупил при обработке конкретного запроса, это заблокирует обработку других запросов на этот узел.

2018-04-09 10:14 UTC, dormidon commented on bdse-kvnode/src/main/proto/kv/distributed.proto
> +option java_package = "ru.csc.bdse.kv.distributed";
Можно добавить опцию `option java_multiple_files = true`, тогда сгенеренный класс не будет вложенным, и его использование в коде станет чуть проще.

2018-04-09 10:17 UTC, dormidon requested changes
Вижу, что идею поняли, координатор реализован хорошо.
Помимо мелкой косметики и удобства использования (автоматическое скачивание protobuf-компилятора при сборке), основное, что нужно исправить - это тесты на контейнеризированные реплики.
Сейчас это один фиксированный тест, а было хорошо написать семейство тестов, варьируя лишь три параметра - "RF", "WCL", "RCL".
Тогда все будет вообще круто.

2018-04-14 09:44 UTC, yeputons commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/ConflictResolver.java
> +    public Distributed.VersionedRecord resolve(List<Distributed.VersionedRecord> records);
В конкретном случае неважен. Причины использования списка вместо `Set` (основной аргумент - первый):

1. В списке разрешены дубликаты, в `Set` они запрещены. Вряд ли две реплики могут выдать ровно один и тот же ответ (с одинаковым timestamp и данными), но если такое случится, лучше эту информацию сохранить. Например, для голосования.
2. Теоретически у меня порядок элементов в списке несёт полезную информацию: примерный порядок получения ответов от реплик.
3. По коду везде используются списки, поэтому так просто чуть удобнее писать.

2018-04-14 09:44 UTC, yeputons commented on INSTALL_TASK3.md
> +* Специфика сборки: должен быть доступен `protoc` в PATH (это компилятор для Google Protobuf).
Сделано, спасибо

2018-04-14 09:51 UTC, yeputons commented on bdse-kvnode/src/main/proto/kv/distributed.proto
> +option java_package = "ru.csc.bdse.kv.distributed";
Спасибо, готово.

2018-04-14 10:00 UTC, yeputons commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/Coordinator.java
> +            executorServices[i] = Executors.newSingleThreadExecutor();
Предлагаю `ScheduledThreadPool` с `corePoolSize=1` (см. код). Насколько я понял, это как пул с одним потоком, но если все заняты — то создаётся ещё поток специально под новые задачи, потом удаляется.

Тогда если ничего не виснет, то запросы идут параллельно, но как только зависло — то начинают создаваться новые потоки, запросы продолжают идти, виснуть... Кстати, кажется, что это может даже сервер уронить, не лучше ли просто забить на запросы? Или ограничить число висящих запросов константой+сделать таймаут на них?

2018-04-14 10:03 UTC, yeputons commented
Косметику поправил (есть некоторое непонимание с тем, как отсылать запросы из координатора — см. обсуждение выше), осталось только улучшить тесты. Ими по плану займётся @LabutinIgor

2018-04-15 14:11 UTC, dormidon commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatorSingleInMemoryNodeApiTest.java
> +        ), new LastTimestampConflictResolver());
А для чего каждый раз создавать экземпляр резолвера? Можно ли применить Singleton?

2018-04-15 14:22 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/Coordinator.java
> +            executorServices[i] = Executors.newSingleThreadExecutor();
А почему `Scheduled`? Мы ведь не используем у него никаких методов типа `scheduleAtFixedRate` или `scheduleAtFixedDelay`. 
Наверно, лучше будет использовать `newCachedThreadPool`, или же самому сконструировать экземпляр ThreadPoolExecutor-а с нужными параметрами, не используя статические фабрики из `Executors`.

>Тогда если ничего не виснет, то запросы идут параллельно, но как только зависло — то начинают создаваться новые потоки, запросы продолжают идти, виснуть... Кстати, кажется, что это может даже сервер уронить, не лучше ли просто забить на запросы? Или ограничить число висящих запросов константой+сделать таймаут на них?

Да, в идеале так и надо. Если создавать `ThreadPoolExecutor` напрямую, то там можно указать максимальное число потоков, а так же можно указать максимальный размер очереди задач и `RejectedExecutionHandler` - поведение, применяемое в случае, если очередь задач переполнена. В этом случае вполне подойдет `AbortPolicy`.

2018-04-15 14:26 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/ConflictResolver.java
> +    public Distributed.VersionedRecord resolve(List<Distributed.VersionedRecord> records);
Ок. 
Аргумент 1 вполне логичен. Иногда для более устойчивого результата ConflictResolver при одинаковом времени может выбирать самое часто встречающееся значение. В этом случае использование множества перетрет нужную информация.
2 и 3 - не аргументы :)

2018-04-15 14:26 UTC, dormidon approved these changes

2018-04-15 14:35 UTC, yeputons commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/distributed/Coordinator.java
> +            executorServices[i] = Executors.newSingleThreadExecutor();
Это я невнимательно прочитал доки: думал, что `Cached` не убивает свои потоки, как `Scheduled`. Но нет, убивает автоматически через 60 секунд. Заменю на `Cached`.

2018-04-15 14:47 UTC, yeputons commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/CoordinatorSingleInMemoryNodeApiTest.java
> +        ), new LastTimestampConflictResolver());
В данном случае можно, потому что у резолвера нет никаких настроек. Серьёзных аргументов в пользу какого-то решения у меня нет:

1. Резолвер создаётся только при создании KeyValueApi, что очень редкая операция.
2. Без singleton код проще.
3. Кажется, что у резолвера легко может появиться конфигурация - тогда всё равно надо делать через конструктор/фабрику и синглтон надо выпиливать.
4. С singleton код явно говорит, что у данного конкретного резолвера все объекты одинаковы.

Лично я бы оставил так, но, может, аргумент 4 и перевешивает.

2018-04-16 07:18 UTC, merged