Csc bdse task4
au-spring-2018-bdse-lms/csc-bdse pull request #5
Opened 2018-04-18 10:49 UTC by yeputons

2018-04-27 07:33 UTC, yeputons commented
Кажется, забыли назначить ревью :(

2018-05-03 09:12 UTC, alesavin requested changes
Самое главный недостаток - нет тестов, а это основное требование в задании

2018-05-03 09:12 UTC, alesavin commented on INSTALL_TASK4.md
> +* Работает `mvn compile`.
тут скорее задание про тесты, а при mvn compile они не запускаются 
или я что-то упускаю?

2018-05-03 09:12 UTC, alesavin commented on README_TASK4.md
> +* Лабутин Игорь
Маркелов Александр уже не в вашей команде?

2018-05-03 09:12 UTC, alesavin commented on README_TASK4.md
> +* Простые тесты: `ShardsCoordiantor*InMemoryNodeApiTest` - наследники
нужно добавить скорее тесты наследуемые от импрлементированного AbstractPartitionedKeyValueApiHttpClientTest

2018-05-03 09:12 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/ShardsCoordinatorSingleInMemoryNodeApiTest.java
> +                new ModNPartitioner(Collections.singleton("node0"))
увидел что используется ModNPartitioner, но других конфигураций не заметил

2018-05-03 09:12 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/partitioned/ShardsCoordinator.java
> +                    return null;
не большой специалист в Java 8, но разве return Void.TYPE; не будет логичнее?

2018-05-03 09:12 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/partitioned/ShardsCoordinator.java
> +        execute(node, shard -> {
action можно исполнять на всех нодах, просто реально исполнит только та, у которой имя совпадает с указанным в команде

2018-05-03 12:44 UTC, yeputons commented on README_TASK4.md
> +* Лабутин Игорь
Да, увы.

2018-05-05 23:26 UTC, alesavin requested changes
Осталось только чуть подточить тесты, вцелом все хорошо. Ну и документацию неплохо поправить (см предыдущие комментарии)

2018-05-05 23:26 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/partitioned/PartitionedKeyValueApiFirstLetterPartitionerTest.java
> +    private static Set<String> keys = Stream.generate(() -> RandomStringUtils.randomAlphanumeric(10)).limit(1000)
тут лучше использовать RandomStringUtils.random(10) дабы получить более распределенные ключи. Если генерировать Alphanumeric то первый символ (что логично) буква или цифра, это приводит к тому что все ключи попадают в один и тот же шард (node0). Тогда в тесте с выбранной конфигурацией:

```
expectedKeysLossProportion = 0.0, actual = 0.0
expectedUndeletedKeysProportion = 0.0, actual = 0.0
```

то есть совсем нет потерь при изменении кластера. При случайных ключах все не так радужно:

```
expectedKeysLossProportion = 0.341, actual = 0.341
expectedUndeletedKeysProportion = 0.341, actual = 0.341
```

2018-05-05 23:26 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/partitioned/PartitionedKeyValueApiModNPartitionerTest.java
> +        assertTrue(lossProportion > 0.5);
это даже заниженная оценка, если, например, взять ключи с hashCode 0-9, то только 3 из 10 сохранят партицию в конфигурации 5 партиций/3 партиции. Итого lossProportion >= 0.7

2018-05-05 23:26 UTC, alesavin commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/partitioned/AbstractPartitionedKeyValueApiHttpClientTest.java
> +
лишний пробел

2018-05-06 18:09 UTC, yeputons commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/partitioned/ShardsCoordinator.java
> +                    return null;
Нет, `Void.TYPE` — это инстанс `Class<Void>`, примерно то же самое, что и `Void.class`. У `Void` ровно одно значение — это `null`.

2018-05-06 20:15 UTC, yeputons reviewed
@alesavin Ответил на все замечания. Почему-то GitHub теперь показывает мои комментарии дважды: один раз — как моё ревью, один раз — как ответы.

2018-05-06 20:15 UTC, yeputons commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/partitioned/ShardsCoordinator.java
> +        execute(node, shard -> {
Done

2018-05-06 20:15 UTC, yeputons commented on README_TASK4.md
> +* Простые тесты: `ShardsCoordiantor*InMemoryNodeApiTest` - наследники
Добавил информацию.

2018-05-06 20:15 UTC, yeputons commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/ShardsCoordinatorSingleInMemoryNodeApiTest.java
> +                new ModNPartitioner(Collections.singleton("node0"))
Они все будут протестированы в более сложном тесте. На маленьком ручном тесте разницы между partitioner'ами скорее всего не будет, это скорее smoke test на адекватность конкретно `ShardsCoordinator`.

2018-05-06 20:15 UTC, yeputons commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/partitioned/AbstractPartitionedKeyValueApiHttpClientTest.java
> +
Fixed.

2018-05-06 20:15 UTC, yeputons commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/partitioned/PartitionedKeyValueApiFirstLetterPartitionerTest.java
> +    private static Set<String> keys = Stream.generate(() -> RandomStringUtils.randomAlphanumeric(10)).limit(1000)
Fixed. Заодно добавил в тесты проверку о том, что ключи теряются с ожидаемой вероятностью. По-хорошему, конечно, надо для consistent hashing там нормально посчитать вероятность, исходя из длин ключей, но, кажется, поставить `factor=100` тоже хорошая идея.

2018-05-06 20:15 UTC, yeputons commented on bdse-integration-tests/src/test/java/ru/csc/bdse/kv/partitioned/PartitionedKeyValueApiModNPartitionerTest.java
> +        assertTrue(lossProportion > 0.5);
Fixed (теперь проверяется в абстрактном тесте).

2018-05-06 20:15 UTC, yeputons commented on INSTALL_TASK4.md
> +* Работает `mvn compile`.
Добавил инструкций

2018-05-06 20:22 UTC, yeputons commented on INSTALL_TASK4.md
> +* Работает `mvn compile`.
Добавил инструкций

2018-05-06 21:45 UTC, alesavin approved these changes

2018-05-07 07:48 UTC, merged